CREATE TABLE beers(
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  name VARCHAR(35) NOT NULL,
  tagline VARCHAR(68) NOT NULL,
  first_brewed VARCHAR(7) NOT NULL,
  description VARCHAR(606) NOT NULL,
  image_url VARCHAR(37) NOT NULL,
  ph NUMERIC(3,1),
  brewers_tips VARCHAR(201) NOT NULL,
  contributed_by VARCHAR(24) NOT NULL
);
INSERT INTO beers(id,name,tagline,first_brewed,description,image_url,ph,brewers_tips,contributed_by) VALUES (1,'Buzz','A Real Bitter Experience.','09/2007','A light, crisp and bitter IPA brewed with English and American hops. A small batch brewed only once.','https://images.punkapi.com/v2/keg.png',4.4,'The earthy and floral aromas from the hops can be overpowering. Drop a little Cascade in at the end of the boil to lift the profile with a bit of citrus.','Sam Mason <samjbmason>');
INSERT INTO beers(id,name,tagline,first_brewed,description,image_url,ph,brewers_tips,contributed_by) VALUES (2,'Trashy Blonde','You Know You Shouldn''t','04/2008','A titillating, neurotic, peroxide punk of a Pale Ale. Combining attitude, style, substance, and a little bit of low self esteem for good measure; what would your mother say? The seductive lure of the sassy passion fruit hop proves too much to resist. All that is even before we get onto the fact that there are no additives, preservatives, pasteurization or strings attached. All wrapped up with the customary BrewDog bite and imaginative twist.','https://images.punkapi.com/v2/2.png',4.4,'Be careful not to collect too much wort from the mash. Once the sugars are all washed out there are some very unpleasant grainy tasting compounds that can be extracted into the wort.','Sam Mason <samjbmason>');
INSERT INTO beers(id,name,tagline,first_brewed,description,image_url,ph,brewers_tips,contributed_by) VALUES (3,'Berliner Weisse With Yuzu - B-Sides','Japanese Citrus Berliner Weisse.','11/2015','Japanese citrus fruit intensifies the sour nature of this German classic.','https://images.punkapi.com/v2/keg.png',3.2,'Clean everything twice. All you want is the clean sourness of lactobacillus.','Sam Mason <samjbmason>');
INSERT INTO beers(id,name,tagline,first_brewed,description,image_url,ph,brewers_tips,contributed_by) VALUES (4,'Pilsen Lager','Unleash the Yeast Series.','09/2013','Our Unleash the Yeast series was an epic experiment into the differences in aroma and flavour provided by switching up your yeast. We brewed up a wort with a light caramel note and some toasty biscuit flavour, and hopped it with Amarillo and Centennial for a citrusy bitterness. Everything else is down to the yeast. Pilsner yeast ferments with no fruity esters or spicy phenols, although it can add a hint of butterscotch.','https://images.punkapi.com/v2/4.png',4.4,'Play around with the fermentation temperature to get the best flavour profile from the individual yeasts.','Ali Skinner <AliSkinner>');
INSERT INTO beers(id,name,tagline,first_brewed,description,image_url,ph,brewers_tips,contributed_by) VALUES (5,'Avery Brown Dredge','Bloggers'' Imperial Pilsner.','02/2011','An Imperial Pilsner in collaboration with beer writers. Tradition. Homage. Revolution. We wanted to showcase the awesome backbone of the Czech brewing tradition, the noble Saaz hop, and also tip our hats to the modern beers that rock our world, and the people who make them.','https://images.punkapi.com/v2/5.png',4.4,'Make sure you have a big enough yeast starter to ferment through the OG and lager successfully.','Sam Mason <samjbmason>');
INSERT INTO beers(id,name,tagline,first_brewed,description,image_url,ph,brewers_tips,contributed_by) VALUES (6,'Electric India','Vibrant Hoppy Saison.','05/2013','Re-brewed as a spring seasonal, this beer – which appeared originally as an Equity Punk shareholder creation – retains its trademark spicy, fruity edge. A perfect blend of Belgian Saison and US IPA, crushed peppercorns and heather honey are also added to produce a genuinely unique beer.','https://images.punkapi.com/v2/6.png',4.4,'Source some really good heather honey to get the right spicy esters in the beer.','Sam Mason <samjbmason>');
INSERT INTO beers(id,name,tagline,first_brewed,description,image_url,ph,brewers_tips,contributed_by) VALUES (7,'AB:12','Imperial Black Belgian Ale.','07/2012','An Imperial Black Belgian Ale aged in old Invergordon Scotch whisky barrels with mountains of raspberries, tayberries and blackberries in each cask. Decadent but light and dry, this beer would make a fantastic base for ageing on pretty much any dark fruit - we used raspberries, tayberries and blackberries beause they were local.','https://images.punkapi.com/v2/7.png',5.3,'Don''t worry too much about controlling the temperature with the Belgian yeast strain - just make sure it doesn''t rise above 30°C!','Sam Mason <samjbmason>');
INSERT INTO beers(id,name,tagline,first_brewed,description,image_url,ph,brewers_tips,contributed_by) VALUES (8,'Fake Lager','Bohemian Pilsner.','03/2013','Fake is the new black. Fake is where it is at. Fake Art, fake brands, fake breasts, and fake lager. We want to play our part in the ugly fallout from the Lager Dream. Say hello to Fake Lager – a zesty, floral 21st century faux masterpiece with added BrewDog bitterness.','https://images.punkapi.com/v2/8.png',4.4,'Once the primary fermentation is complete get this beer as cold as you can and let it mature for as long as you''ve got.','Sam Mason <samjbmason>');
INSERT INTO beers(id,name,tagline,first_brewed,description,image_url,ph,brewers_tips,contributed_by) VALUES (9,'AB:07','Whisky Cask-Aged Scotch Ale.','03/2010','Whisky cask-aged imperial scotch ale. Beer perfect for when the rain is coming sideways. Liquorice, plum and raisin temper the warming alcohol, producing a beer capable of holding back the Scottish chill.','https://images.punkapi.com/v2/9.png',5.6,'Authentic heather honey adds a beautiful floral top note that is unachievable any other way.','Sam Mason <samjbmason>');
INSERT INTO beers(id,name,tagline,first_brewed,description,image_url,ph,brewers_tips,contributed_by) VALUES (10,'Bramling X','Single Hop IPA Series - 2011.','01/2011','Good old Bramling Cross is elegant, refined, assured, (boring) and understated. Understated that is unless you hop the living daylights out of a beer with it. This is Bramling Cross re-invented and re-imagined, and shows just what can be done with English hops if you use enough of them. Poor Bramling Cross normally gets lost in a woeful stream of conformist brown ales made by sleepy cask ale brewers. But not anymore. This beer shows that British hops do have some soul, and is a fruity riot of blackberries, pears, and plums. Reminds me of the bramble, apple and ginger jam my grandmother used to make.','https://images.punkapi.com/v2/10.png',4.4,'Getting good Bramling Cross is key. Most English hops are in leaf form (not pelletised), so getting fresh hops close to harvest (September) will give this beer the right amount of dark berry intensity.','Sam Mason <samjbmason>');
INSERT INTO beers(id,name,tagline,first_brewed,description,image_url,ph,brewers_tips,contributed_by) VALUES (11,'Misspent Youth','Milk & Honey Scotch Ale.','04/2013','The brainchild of our small batch brewer, George Woods. A dangerously drinkable milk sugar- infused Scotch Ale.','https://images.punkapi.com/v2/keg.png',4.4,'Lots of malt in this one. Mash-in in stages, and spread the pale ale malt throughout the mash to provide stability. If the mash starts to sink, stop, wait a few minutes while mixing, then start again.','Sam Mason <samjbmason>');
INSERT INTO beers(id,name,tagline,first_brewed,description,image_url,ph,brewers_tips,contributed_by) VALUES (12,'Arcade Nation','Seasonal Black IPA.','12/2015','Running the knife-edge between an India Pale Ale and a Stout, this particular style is one we truly love. Black IPAs are a great showcase for the skill of our brew team, balancing so many complex and twisting flavours in the same moment. The citrus, mango and pine from the hops – three of our all-time favourites – play off against the roasty dryness from the malt bill at each and every turn.','https://images.punkapi.com/v2/12.png',4.2,'Be as accurate as possible when weighing out your malts to ensure you strike the right balance.','Sam Mason <samjbmason>');
INSERT INTO beers(id,name,tagline,first_brewed,description,image_url,ph,brewers_tips,contributed_by) VALUES (13,'Movember','Moustache-Worthy Beer.','11/2009','A deliciously robust, black malted beer with a decadent dark, dry cocoa flavour that provides an enticing backdrop to the Cascade hops.','https://images.punkapi.com/v2/13.png',5.2,'If you can’t find really fresh cascade, substitute it for Amarillo or Ahtanum.','Sam Mason <samjbmason>');
INSERT INTO beers(id,name,tagline,first_brewed,description,image_url,ph,brewers_tips,contributed_by) VALUES (14,'Alpha Dog','Existential Red Ale.','02/2010','A fusion of caramel malt flavours and punchy New Zealand hops. A session beer you can get your teeth into.','https://images.punkapi.com/v2/14.png',4.4,'Crush the malt as close to brewing time as possible. The fresher the malt, the more intense caramel flavours will be released in the wort.','Sam Mason <samjbmason>');
INSERT INTO beers(id,name,tagline,first_brewed,description,image_url,ph,brewers_tips,contributed_by) VALUES (15,'Mixtape 8','An Epic Fusion Of Old Belgian, American New Wave, And Scotch Whisky.','01/2012','This recipe is for the Belgian Tripel base. A blend of two huge oak aged beers – half a hopped up Belgian Tripel, and half a Triple India Pale Ale. Both aged in single grain whisky barrels for two years and blended, each beer brings its own character to the mix. The Belgian Tripel comes loaded with complex spicy, fruity esters, and punchy citrus hop character.','https://images.punkapi.com/v2/15.png',4.4,'Brew twice as much Belgian Tripel as you were planning on ageing - it''s awesome on its own too!','Sam Mason <samjbmason>');
INSERT INTO beers(id,name,tagline,first_brewed,description,image_url,ph,brewers_tips,contributed_by) VALUES (16,'Libertine Porter','Dry-Hopped Aggressive Porter.','01/2012','An avalanche of cross-continental hop varieties give this porter a complex spicy, resinous and citrusy aroma, with a huge malt bill providing a complex roasty counterpoint. Digging deeper into the flavour draws out cinder toffee, bitter chocolate and hints of woodsmoke.','https://images.punkapi.com/v2/16.png',4.4,'Mash in at a higher temperature to leave more unfermentable sugars in the wort. This gives the beer a sweeter porter profile.','Sam Mason <samjbmason>');
INSERT INTO beers(id,name,tagline,first_brewed,description,image_url,ph,brewers_tips,contributed_by) VALUES (17,'AB:06','Imperial Black IPA.','04/2011','Our sixth Abstrakt, this imperial black IPA combined dark malts with a monumental triple dry-hop, using an all-star team of some of our favourite American hops. Roasty and resinous.','https://images.punkapi.com/v2/17.png',NULL,'Boil down to desired OG (about 17 litres).','Sam Mason <samjbmason>');
INSERT INTO beers(id,name,tagline,first_brewed,description,image_url,ph,brewers_tips,contributed_by) VALUES (18,'Russian Doll – India Pale Ale','Nesting Hop Bomb.','08/2014','The levels of hops vary throughout the range. We love hops, so all four beers are big, bitter badasses, but by tweaking the amount of each hop used later in the boil and during dry- hopping, we can balance the malty backbone with some unexpected flavours. Simcoe is used in the whirlpool for all four beers, and yet still lends different characters to each','https://images.punkapi.com/v2/18.png',5.2,'Create balance through experimentation with the hop amounts and malt backbone.','Sam Mason <samjbmason>');
INSERT INTO beers(id,name,tagline,first_brewed,description,image_url,ph,brewers_tips,contributed_by) VALUES (19,'Hello My Name Is Mette-Marit','Lingonberry Double IPA.','06/2013','We sent this beer to Norway where it was known as ''Hello, my name is Censored’. You can make up your own mind as to why. This brew was a red berry explosion, with a reisnous bitter edge layered with dry berry tartness.','https://images.punkapi.com/v2/19.png',4.4,'Using crushed cranberries will dry out the beer further, drawing out their natural astringent character.','Sam Mason <samjbmason>');
INSERT INTO beers(id,name,tagline,first_brewed,description,image_url,ph,brewers_tips,contributed_by) VALUES (20,'Rabiator','Imperial Wheat Beer','03/2011','Imperial Wheat beer / Weizenbock brewed by a homesick German in leather trousers. Think banana bread, bubble gum and David Hasselhoff.','https://images.punkapi.com/v2/keg.png',4.4,'If you are struggling to get that authentic head retention increase your mash temperature to about 70°C.','Sam Mason <samjbmason>');
INSERT INTO beers(id,name,tagline,first_brewed,description,image_url,ph,brewers_tips,contributed_by) VALUES (21,'Vice Bier','Hoppy Wheat Bier.','04/2013','Our take on the classic German Kristallweizen. A clear German wheat beer, layers of bubblegum and vanilla perfectly balanced with the American and New Zealand hops.','https://images.punkapi.com/v2/keg.png',4,'Ferment at higher or lower temperatures to select the esters that will create clove- like or banana-like flavours.','Sam Mason <samjbmason>');
INSERT INTO beers(id,name,tagline,first_brewed,description,image_url,ph,brewers_tips,contributed_by) VALUES (22,'Devine Rebel (w/ Mikkeller)','Oak-aged Barley Wine.','12/2008','Two of Europe''s most experimental, boundary-pushing brewers, BrewDog and Mikkeller, combined forces to produce a rebellious beer that combined their respective talents and brewing skills. The 12.5% Barley Wine fermented well, and the champagne yeast drew it ever closer to 12.5%. The beer was brewed with a single hop variety and was going to be partially aged in oak casks.','https://images.punkapi.com/v2/22.png',4.4,'Rack off to a secondary fermenter before pitching in some champagne.','Sam Mason <samjbmason>');
INSERT INTO beers(id,name,tagline,first_brewed,description,image_url,ph,brewers_tips,contributed_by) VALUES (23,'Storm','Islay Whisky Aged IPA.','12/2007','Dark and powerful Islay magic infuses this tropical sensation of an IPA. Using the original Punk IPA as a base, we boosted the ABV to 8% giving it some extra backbone to stand up to the peated smoke imported directly from Islay.','https://images.punkapi.com/v2/23.png',4.4,'After primary fermentation is complete, rack off into a secondary fermeter and add the oak chips to replicate the authentic Islay barrel experience.','Sam Mason <samjbmason>');
INSERT INTO beers(id,name,tagline,first_brewed,description,image_url,ph,brewers_tips,contributed_by) VALUES (24,'The End Of History','The World''s Strongest Beer.','06/2011','The End of History: The name derives from the famous work of philosopher Francis Fukuyama, this is to beer what democracy is to history. Complexity defined. Floral, grapefruit, caramel and cloves are intensified by boozy heat.','https://images.punkapi.com/v2/24.png',4.4,'You''ll have to get this one all the way down to -70°C. Taxidermy is not optional.','Sam Mason <samjbmason>');
INSERT INTO beers(id,name,tagline,first_brewed,description,image_url,ph,brewers_tips,contributed_by) VALUES (25,'Bad Pixie','Spiced Wheat Beer.','10/2008','2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.','https://images.punkapi.com/v2/25.png',4.4,'Make sure you have plenty of room in the fermenter. Beers containing wheat can often foam aggressively during fermentation.','Sam Mason <samjbmason>');
